import mongoose, { Schema, Document, Model, Types } from 'mongoose';

export interface IPostmortemTimelineEntry {
  time: Date;
  description: string;
}

export interface IPostmortemActionItem {
  description: string;
  owner_id?: Types.ObjectId;
  due_date?: Date;
  status: 'open' | 'in_progress' | 'done';
  ticket_id?: Types.ObjectId;
  reminder_sent?: boolean;
  overdue_reminder_sent?: boolean;
}

export interface IPostmortemActionItemV2 {
  title: string;
  description: string;
  owner_id?: Types.ObjectId;
  due_date?: Date;
  status: 'open' | 'in_progress' | 'done' | 'wont_do';
  priority: 'critical' | 'high' | 'medium' | 'low';
  linked_ticket_id?: Types.ObjectId | null;
  completed_at?: Date | null;
  effectiveness?: {
    recurrence_count: number;
    prevented: boolean | null;
    assessed_at: Date | null;
  } | null;
}

export interface IPostmortemAutoGenerated {
  timeline_draft: string | null;
  root_cause_draft: string | null;
  impact_draft: string | null;
  resolution_draft: string | null;
  lessons_draft: string | null;
}

export interface IPostmortemRecurrencePattern {
  is_recurring: boolean;
  previous_incident_ids: Types.ObjectId[];
  pattern_description: string | null;
  open_action_items_from_previous: number;
}

export interface IPostmortem {
  tenant_id: Types.ObjectId;
  title: string;
  incident_id?: Types.ObjectId;
  severity: 'critical' | 'high' | 'medium' | 'low';
  status: 'draft' | 'in-review' | 'published';
  summary: string;
  timeline: IPostmortemTimelineEntry[];
  root_cause: string;
  contributing_factors: string[];
  action_items: IPostmortemActionItem[];
  action_items_v2: IPostmortemActionItemV2[];
  auto_generated: IPostmortemAutoGenerated;
  recurrence_pattern: IPostmortemRecurrencePattern | null;
  author_id: Types.ObjectId;
  reviewed_by: Types.ObjectId[];
  published_at?: Date;
  created_at: Date;
  updated_at: Date;
}

export interface PostmortemDocument extends IPostmortem, Document {
  _id: Types.ObjectId;
}

const postmortemSchema = new Schema<PostmortemDocument>(
  {
    tenant_id: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true },
    title: { type: String, required: true, trim: true, maxlength: 500 },
    incident_id: { type: Schema.Types.ObjectId, ref: 'Ticket' },
    severity: {
      type: String,
      enum: ['critical', 'high', 'medium', 'low'],
      default: 'medium',
    },
    status: {
      type: String,
      enum: ['draft', 'in-review', 'published'],
      default: 'draft',
    },
    summary: { type: String, default: '' },
    timeline: [
      {
        time: { type: Date, required: true },
        description: { type: String, required: true },
      },
    ],
    root_cause: { type: String, default: '' },
    contributing_factors: [{ type: String }],
    action_items: [
      {
        description: { type: String, required: true },
        owner_id: { type: Schema.Types.ObjectId, ref: 'User' },
        due_date: Date,
        status: {
          type: String,
          enum: ['open', 'in_progress', 'done'],
          default: 'open',
        },
        ticket_id: { type: Schema.Types.ObjectId, ref: 'Ticket' },
        reminder_sent: { type: Boolean, default: false },
        overdue_reminder_sent: { type: Boolean, default: false },
      },
    ],
    action_items_v2: [
      {
        title: { type: String, required: true },
        description: { type: String, default: '' },
        owner_id: { type: Schema.Types.ObjectId, ref: 'User' },
        due_date: Date,
        status: {
          type: String,
          enum: ['open', 'in_progress', 'done', 'wont_do'],
          default: 'open',
        },
        priority: {
          type: String,
          enum: ['critical', 'high', 'medium', 'low'],
          default: 'medium',
        },
        linked_ticket_id: { type: Schema.Types.ObjectId, ref: 'Ticket', default: null },
        completed_at: { type: Date, default: null },
        effectiveness: {
          type: {
            recurrence_count: { type: Number, default: 0 },
            prevented: { type: Boolean, default: null },
            assessed_at: { type: Date, default: null },
          },
          default: null,
          _id: false,
        },
      },
    ],
    auto_generated: {
      type: {
        timeline_draft: { type: String, default: null },
        root_cause_draft: { type: String, default: null },
        impact_draft: { type: String, default: null },
        resolution_draft: { type: String, default: null },
        lessons_draft: { type: String, default: null },
      },
      default: () => ({}),
      _id: false,
    },
    recurrence_pattern: {
      type: {
        is_recurring: { type: Boolean, default: false },
        previous_incident_ids: [{ type: Schema.Types.ObjectId, ref: 'Incident' }],
        pattern_description: { type: String, default: null },
        open_action_items_from_previous: { type: Number, default: 0 },
      },
      default: null,
      _id: false,
    },
    author_id: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    reviewed_by: [{ type: Schema.Types.ObjectId, ref: 'User' }],
    published_at: Date,
  },
  {
    collection: 'postmortems',
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
  }
);

postmortemSchema.index({ tenant_id: 1 });
postmortemSchema.index({ tenant_id: 1, status: 1 });

export const Postmortem: Model<PostmortemDocument> = mongoose.model<PostmortemDocument>(
  'Postmortem',
  postmortemSchema
);
