import { Router, Request, Response } from 'express';
import { z } from 'zod';
import rateLimit from 'express-rate-limit';
import { rbac } from '../middleware/rbac.middleware';
import { requirePlanFeature } from '../middleware/planLimit.middleware';
import { AppError } from '../middleware/errorHandler.middleware';
import { Ticket } from '../models/ticket.model';
import { Postmortem } from '../models/postmortem.model';
import { Runbook } from '../models/runbook.model';
import { Incident } from '../models/incident.model';
import { AIConversation } from '../models/ai-conversation.model';
import { Types } from 'mongoose';
import { logger } from '../utils/logger';
import {
  generateCompletion,
  generateChatCompletion,
  streamChatCompletion,
  isAIAvailable,
  ChatMessage,
} from '../services/ai.service';
import {
  buildIncidentContext,
  formatContextForPrompt,
} from '../services/ai-context.service';
import { parseRunbookStepsFromMarkdown } from '../utils/runbook-markdown';
import { checkAiBudget, consumeAiTokens, estimateTokens } from '../services/ai-budget.service';
import {
  TRIAGE_SYSTEM_PROMPT,
  RCA_SYSTEM_PROMPT,
  POSTMORTEM_SYSTEM_PROMPT,
  RUNBOOK_SYSTEM_PROMPT,
  COPILOT_SYSTEM_PROMPT,
  SUGGEST_TITLE_PROMPT,
  SUGGEST_SEVERITY_PROMPT,
} from '../services/ai-prompts';

const router = Router();

// ─── Rate limiting: 10 requests/min per user+tenant ──────────────────────────

const aiRateLimit = rateLimit({
  windowMs: 60 * 1000,
  max: 10,
  keyGenerator: (req: Request) => `${req.tenantId}:${req.userId}`,
  message: {
    type: 'https://sreoncall.io/problems/rate-limited',
    title: 'Too Many Requests',
    status: 429,
    detail: 'AI rate limit exceeded. Max 10 requests per minute.',
  },
  standardHeaders: true,
  legacyHeaders: false,
});

router.use(aiRateLimit);

// ─── Helpers ─────────────────────────────────────────────────────────────────

function priorityLabel(p: number | string): string {
  if (typeof p === 'string') return p;
  const map: Record<number, string> = { 1: 'high', 2: 'high', 3: 'medium', 4: 'low', 5: 'low' };
  return map[p] || 'medium';
}

function severityLabel(p: number): string {
  const map: Record<number, string> = { 1: 'CRITICAL', 2: 'HIGH', 3: 'MEDIUM', 4: 'LOW', 5: 'INFO' };
  return map[p] || 'MEDIUM';
}

/** Look up incident from new Incident model, falling back to legacy Ticket model. */
async function getIncidentDoc(tenantId: Types.ObjectId, id: string) {
  // Try new Incident model first
  const incident = await Incident.findOne({ _id: id, tenant_id: tenantId });
  if (incident) return { source: 'incident' as const, doc: incident };

  // Fall back to legacy Ticket model
  const ticket = await Ticket.findOne({ _id: id, tenant_id: tenantId, type: 'incident' })
    .populate('reporter_id', 'name email')
    .populate('assignee_id', 'name email');
  if (ticket) return { source: 'ticket' as const, doc: ticket };

  throw AppError.notFound('Incident');
}

// ─── Fallback generators (used when OPENAI_API_KEY is not set) ────────────

function fallbackTriage(incident: any): string {
  const priority = (incident.priority || incident.severity || 3) as number;
  const pLabel = priorityLabel(priority);
  const severity = severityLabel(priority);
  const title = incident.title || 'Unknown incident';
  return [
    `## Auto-Triage Analysis`,
    ``,
    `**Incident:** ${title}`,
    `**Severity:** ${severity} (${pLabel})`,
    `**Status:** ${incident.status}`,
    ``,
    `### Recommended Actions`,
    `1. Verify the scope and impact of the incident`,
    `2. Check related services and dependencies for cascading failures`,
    `3. Engage the on-call engineer for ${priority <= 2 ? 'immediate' : 'standard'} response`,
    `4. Open a war room channel if not already done`,
    ``,
    `### Initial Assessment`,
    `Based on the incident description, this appears to be a ${severity.toLowerCase()} severity issue. ` +
    `Priority escalation to ${priority === 1 ? 'all stakeholders' : priority === 2 ? 'team leads' : 'on-call team'} is recommended.`,
    ``,
    `*Generated by SREonCall AI Copilot (template mode — configure OPENAI_API_KEY for AI-powered analysis)*`,
  ].join('\n');
}

function fallbackRCA(incident: any): string {
  const title = incident.title || 'Unknown incident';
  const description = incident.description || '';
  const resolvedAt = incident.resolvedAt || incident.resolved_at;
  return [
    `## Root Cause Analysis`,
    ``,
    `**Incident:** ${title}`,
    `**Analysis Date:** ${new Date().toISOString().split('T')[0]}`,
    ``,
    `### Summary`,
    description ? `${description.slice(0, 300)}${description.length > 300 ? '...' : ''}` : 'No description provided.',
    ``,
    `### Probable Root Causes`,
    `1. **Primary cause**: Investigate recent deployments, configuration changes, or infrastructure events in the 24h window preceding the incident`,
    `2. **Contributing factors**: Load spike, dependency failures, or resource exhaustion`,
    `3. **Detection gap**: Alert thresholds may need tuning for earlier detection`,
    ``,
    `### Timeline Reconstruction`,
    `- T+0: Incident declared`,
    `- T+?: Alert fired (check monitoring)`,
    `- T+?: On-call notified`,
    `- T+?: Incident resolved (${resolvedAt ? new Date(resolvedAt).toISOString() : 'pending'})`,
    ``,
    `### Next Steps`,
    `1. Review deployment logs and change records from the incident window`,
    `2. Collect metrics from Prometheus/Grafana for the affected period`,
    `3. Document findings in a post-mortem`,
    ``,
    `*Generated by SREonCall AI Copilot (template mode — configure OPENAI_API_KEY for AI-powered analysis)*`,
  ].join('\n');
}

// ─── GET /api/v1/ai/status ───────────────────────────────────────────────────

router.get('/status', rbac('incidents:read'), (_req: Request, res: Response) => {
  const keyConfigured = isAIAvailable();
  res.json({
    ai_available: keyConfigured,
    key_configured: keyConfigured,
    model: keyConfigured ? 'claude-sonnet-4-20250514' : 'fallback',
    note: keyConfigured ? 'API key is set. AI will fall back to templates if the API is unreachable.' : 'No API key configured. Using template fallbacks.',
  });
});

// ─── POST /api/v1/ai/triage/incident/:id ─────────────────────────────────────

router.post('/triage/incident/:id', rbac('incidents:read'), async (req: Request, res: Response) => {
  const id = req.params['id'] as string;
  const { doc } = await getIncidentDoc(req.tenantId, id);

  let result: string;

  if (isAIAvailable()) {
    const ctx = await buildIncidentContext(req.tenantId, id);
    const contextText = ctx ? formatContextForPrompt(ctx) : `Incident: ${doc.title}\nStatus: ${doc.status}`;
    await checkAiBudget(req.tenantId, estimateTokens(contextText));
    const completion = await generateCompletion({
      system: TRIAGE_SYSTEM_PROMPT,
      userMessage: `Analyze and triage this incident:\n\n${contextText}`,
    });
    if (completion.model !== 'fallback') {
      await consumeAiTokens(req.tenantId, completion.input_tokens, completion.output_tokens);
    }
    result = completion.model === 'fallback' ? fallbackTriage(doc) : completion.text;
  } else {
    result = fallbackTriage(doc);
  }

  res.json({ result, incident_id: id, generated_at: new Date().toISOString() });
});

// ─── POST /api/v1/ai/rca/incident/:id ───────────────────────────────────────

router.post('/rca/incident/:id', rbac('incidents:read'), requirePlanFeature('ai_rca_enabled'), async (req: Request, res: Response) => {
  const id = req.params['id'] as string;
  const { doc } = await getIncidentDoc(req.tenantId, id);

  let result: string;

  if (isAIAvailable()) {
    const ctx = await buildIncidentContext(req.tenantId, id);
    const contextText = ctx ? formatContextForPrompt(ctx) : `Incident: ${doc.title}\nStatus: ${doc.status}`;
    await checkAiBudget(req.tenantId, estimateTokens(contextText));
    const completion = await generateCompletion({
      system: RCA_SYSTEM_PROMPT,
      userMessage: `Perform a root cause analysis for this incident:\n\n${contextText}`,
    });
    if (completion.model !== 'fallback') {
      await consumeAiTokens(req.tenantId, completion.input_tokens, completion.output_tokens);
    }
    result = completion.model === 'fallback' ? fallbackRCA(doc) : completion.text;
  } else {
    result = fallbackRCA(doc);
  }

  res.json({ result, incident_id: id, generated_at: new Date().toISOString() });
});

// ─── POST /api/v1/ai/postmortem/draft/:id ────────────────────────────────────

router.post('/postmortem/draft/:id', rbac('postmortems:create'), async (req: Request, res: Response) => {
  const id = req.params['id'] as string;
  const { doc } = await getIncidentDoc(req.tenantId, id);

  const createdAt: Date = (doc as any).createdAt || new Date();
  const resolvedAt = (doc as any).resolvedAt || (doc as any).resolved_at;
  const priority = ((doc as any).priority || (doc as any).severity || 3) as number;

  let summary: string;
  let rootCause: string;

  if (isAIAvailable()) {
    const ctx = await buildIncidentContext(req.tenantId, id);
    const contextText = ctx ? formatContextForPrompt(ctx) : `Incident: ${doc.title}`;

    await checkAiBudget(req.tenantId, estimateTokens(contextText) * 2);
    const [summaryResult, rcaResult] = await Promise.all([
      generateCompletion({
        system: POSTMORTEM_SYSTEM_PROMPT,
        userMessage: `Draft a post-mortem summary for this incident:\n\n${contextText}`,
        maxTokens: 2048,
      }),
      generateCompletion({
        system: RCA_SYSTEM_PROMPT,
        userMessage: `Perform a root cause analysis for this incident:\n\n${contextText}`,
        maxTokens: 2048,
      }),
    ]);

    if (summaryResult.model !== 'fallback') {
      await consumeAiTokens(req.tenantId, summaryResult.input_tokens, summaryResult.output_tokens);
    }
    if (rcaResult.model !== 'fallback') {
      await consumeAiTokens(req.tenantId, rcaResult.input_tokens, rcaResult.output_tokens);
    }

    if (summaryResult.model === 'fallback' || rcaResult.model === 'fallback') {
      summary = `Incident ${priorityLabel(priority)} — ${doc.title}. ` +
        `Started ${new Date(createdAt).toISOString()}. ` +
        (resolvedAt ? `Resolved ${new Date(resolvedAt).toISOString()}.` : 'Ongoing.');
      rootCause = fallbackRCA(doc);
    } else {
      summary = summaryResult.text;
      rootCause = rcaResult.text;
    }
  } else {
    const title = `Post-mortem: ${doc.title}`;
    summary = `Incident ${priorityLabel(priority)} — ${doc.title}. ` +
      `Started ${new Date(createdAt).toISOString()}. ` +
      (resolvedAt ? `Resolved ${new Date(resolvedAt).toISOString()}.` : 'Ongoing.');
    rootCause = fallbackRCA(doc);
  }

  const pm = await Postmortem.create({
    tenant_id: req.tenantId,
    title: `Post-mortem: ${doc.title}`,
    incident_id: doc._id,
    severity: priority === 1 ? 'critical' : priority === 2 ? 'high' : 'medium',
    status: 'draft',
    summary,
    root_cause: rootCause,
    contributing_factors: ['Recent change', 'Monitoring gap', 'Dependency failure'],
    timeline: [
      { time: new Date(createdAt).toISOString(), description: 'Incident declared' },
    ],
    action_items: [
      { description: 'Review monitoring thresholds', status: 'open' },
      { description: 'Document runbook for this failure mode', status: 'open' },
    ],
    author_id: req.userId,
  });

  res.status(201).json({ postmortem_id: pm._id.toString(), message: 'Post-mortem draft created' });
});

// ─── POST /api/v1/ai/runbooks/generate-from-incident/:id ────────────────────

router.post('/runbooks/generate-from-incident/:id', rbac('runbooks:create'), async (req: Request, res: Response) => {
  const id = req.params['id'] as string;
  const { doc } = await getIncidentDoc(req.tenantId, id);
  const priority = ((doc as any).priority || (doc as any).severity || 3) as number;

  let content: string;
  let generated = false;

  if (isAIAvailable()) {
    const ctx = await buildIncidentContext(req.tenantId, id);
    const contextText = ctx ? formatContextForPrompt(ctx) : `Incident: ${doc.title}`;
    await checkAiBudget(req.tenantId, estimateTokens(contextText));
    const completion = await generateCompletion({
      system: RUNBOOK_SYSTEM_PROMPT,
      userMessage: [
        `Generate a COMPREHENSIVE, production-ready operational runbook for handling incidents like this one.`,
        `Target length 1500–3000 words. Every section must be fully populated with actionable, incident-specific content — no placeholders, no generic advice.`,
        `Use the services, responders, timeline entries, recent changes, and runbook references from the INCIDENT CONTEXT block below verbatim. Commands must be copy-pasteable with real service names, not "your-service-name".`,
        ``,
        `=== INCIDENT CONTEXT ===`,
        contextText,
      ].join('\n'),
      // 4096 (the default) truncates comprehensive 10-section runbooks mid-sentence.
      // Allow up to ~16k tokens so the full structured document lands intact.
      maxTokens: 16000,
    });
    if (completion.model !== 'fallback') {
      await consumeAiTokens(req.tenantId, completion.input_tokens, completion.output_tokens);
      generated = true;
    }
    if (!generated) {
      content = buildFallbackRunbookMarkdown(doc, priority);
    } else {
      content = completion.text;
    }
  } else {
    content = buildFallbackRunbookMarkdown(doc, priority);
  }

  // Parse the markdown body into structured, executable steps so the runbook
  // detail page (Execute button, step-by-step UI) is usable out of the box.
  const parsedSteps = parseRunbookStepsFromMarkdown(content);

  const steps = parsedSteps.map((s, i) => ({
    order: i,
    title: s.title,
    instructions: s.instructions,
    type: s.type,
    requires_approval: false,
    approval_roles: [],
    timeout_seconds: 300,
    working_directory: '',
    environment_vars: {},
    api_method: 'GET',
    api_url: '',
    api_headers: {},
    api_body: '',
    attachments: [],
  }));

  const runbook = await Runbook.create({
    tenant_id: req.tenantId,
    title: `Runbook: ${doc.title}`,
    description: `Auto-generated runbook from incident: ${doc.title}`,
    content,
    steps,
    tags: ['auto-generated', 'incident-response'],
    service_ids: [],
    author_id: req.userId,
    created_by: req.userId,
    ai_generated: true,
  });

  res.status(201).json({
    runbook_id: runbook._id.toString(),
    step_count: steps.length,
    ai_generated: generated,
    message: 'Runbook generated',
  });
});

function buildFallbackRunbookMarkdown(doc: any, priority: number): string {
  const title = `Runbook: ${doc.title}`;
  return [
    `# ${title}`,
    ``,
    `## 1. Overview`,
    `This runbook documents the response procedure for incidents similar to: **${doc.title}**.`,
    ``,
    `## 2. Symptoms & Detection`,
    (doc as any).description || 'See incident description.',
    ``,
    `## 3. Severity & Impact Assessment`,
    `Priority: **${priorityLabel(priority)}** — affects production services.`,
    ``,
    `## 4. Immediate Triage (first 5 minutes)`,
    `1. **Acknowledge** the incident and notify the team`,
    `2. **Assess scope**: determine affected services and users`,
    `3. **Mitigate**: apply immediate workaround if available`,
    `4. **Investigate**: review recent changes, deployments, and logs`,
    `5. **Resolve**: implement fix and verify recovery`,
    ``,
    `## 8. Escalation Matrix`,
    `If unresolved after 30 minutes, escalate to the on-call lead.`,
    ``,
    `## 9. Post-Incident Actions`,
    `- **Post-mortem**: document learnings after resolution`,
    ``,
    `*Generated by SREonCall AI Copilot (template mode — AI temporarily unavailable)*`,
  ].join('\n');
}

// ─── POST /api/v1/ai/suggest/title ───────────────────────────────────────────

const suggestTitleSchema = z.object({
  description: z.string().min(1).max(5000),
});

router.post('/suggest/title', rbac('incidents:create'), async (req: Request, res: Response) => {
  const { description } = suggestTitleSchema.parse(req.body);

  if (!isAIAvailable()) {
    // Simple fallback: first line, trimmed to 100 chars
    const title = description.split('\n')[0].slice(0, 100);
    res.json({ title, ai_generated: false });
    return;
  }

  await checkAiBudget(req.tenantId, estimateTokens(description));
  const completion = await generateCompletion({
    system: SUGGEST_TITLE_PROMPT,
    userMessage: description,
    maxTokens: 100,
  });

  if (completion.model !== 'fallback') {
    await consumeAiTokens(req.tenantId, completion.input_tokens, completion.output_tokens);
  }

  if (completion.model === 'fallback') {
    const title = description.split('\n')[0].slice(0, 100);
    res.json({ title, ai_generated: false });
  } else {
    res.json({ title: completion.text.trim(), ai_generated: true });
  }
});

// ─── POST /api/v1/ai/suggest/severity ────────────────────────────────────────

const suggestSeveritySchema = z.object({
  title: z.string().min(1).max(500),
  description: z.string().max(5000).default(''),
});

router.post('/suggest/severity', rbac('incidents:create'), async (req: Request, res: Response) => {
  const { title, description } = suggestSeveritySchema.parse(req.body);

  if (!isAIAvailable()) {
    res.json({ severity: 3, reasoning: 'Default severity (AI not configured)', ai_generated: false });
    return;
  }

  await checkAiBudget(req.tenantId, estimateTokens(`${title} ${description}`));
  const completion = await generateCompletion({
    system: SUGGEST_SEVERITY_PROMPT,
    userMessage: `Title: ${title}\nDescription: ${description}`,
    maxTokens: 200,
  });

  if (completion.model !== 'fallback') {
    await consumeAiTokens(req.tenantId, completion.input_tokens, completion.output_tokens);
  }

  if (completion.model === 'fallback') {
    res.json({ severity: 3, reasoning: 'Default severity (AI temporarily unavailable)', ai_generated: false });
    return;
  }

  try {
    const parsed = JSON.parse(completion.text);
    res.json({
      severity: Math.min(5, Math.max(1, Number(parsed.severity) || 3)),
      reasoning: parsed.reasoning || '',
      ai_generated: true,
    });
  } catch {
    res.json({ severity: 3, reasoning: 'Could not parse AI response', ai_generated: true });
  }
});

// ─── POST /api/v1/ai/copilot/chat ─── (SSE streaming) ──────────────────────

const copilotChatSchema = z.object({
  message: z.string().min(1).max(10000),
  incident_id: z.string().optional(),
  conversation_id: z.string().optional(),
});

router.post('/copilot/chat', rbac('ai:chat'), async (req: Request, res: Response) => {
  const { message, incident_id, conversation_id } = copilotChatSchema.parse(req.body);

  // Set SSE headers
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.setHeader('X-Accel-Buffering', 'no');
  res.flushHeaders();

  // Load or create conversation
  let conversation;
  if (conversation_id) {
    conversation = await AIConversation.findOne({
      _id: conversation_id,
      tenant_id: req.tenantId,
      user_id: req.userId,
    });
  }

  if (!conversation) {
    conversation = await AIConversation.create({
      tenant_id: req.tenantId,
      user_id: req.userId,
      incident_id: incident_id ? new Types.ObjectId(incident_id) : null,
      title: message.slice(0, 100),
      messages: [],
    });
  }

  // Build context-aware system prompt
  let systemPrompt = COPILOT_SYSTEM_PROMPT;
  if (incident_id) {
    const ctx = await buildIncidentContext(req.tenantId, incident_id);
    if (ctx) {
      systemPrompt += `\n\n--- CURRENT INCIDENT CONTEXT ---\n${formatContextForPrompt(ctx)}`;
    }
  }

  // Add user message to conversation
  conversation.messages.push({
    role: 'user',
    content: message,
    timestamp: new Date(),
  });

  // Build messages array for the API (keep last 20 messages for context window)
  const chatMessages: ChatMessage[] = conversation.messages.slice(-20).map((m) => ({
    role: m.role,
    content: m.content,
  }));

  // Budget check before streaming
  await checkAiBudget(req.tenantId, estimateTokens(message) * 2);

  // Stream response
  let fullResponse = '';

  await streamChatCompletion(systemPrompt, chatMessages, {
    onText: (text) => {
      fullResponse += text;
      res.write(`data: ${JSON.stringify({ type: 'text_delta', text })}\n\n`);
    },
    onDone: async (usage) => {
      await consumeAiTokens(req.tenantId, usage.input_tokens, usage.output_tokens);

      // Save assistant response to conversation
      conversation!.messages.push({
        role: 'assistant',
        content: fullResponse,
        timestamp: new Date(),
      });
      conversation!.total_tokens += (usage.input_tokens + usage.output_tokens);
      await conversation!.save();

      res.write(`data: ${JSON.stringify({
        type: 'done',
        conversation_id: conversation!._id.toString(),
        usage,
      })}\n\n`);
      res.end();
    },
    onError: (error) => {
      logger.error('Copilot stream error', { error: error.message });
      res.write(`data: ${JSON.stringify({ type: 'error', message: 'AI processing failed' })}\n\n`);
      res.end();
    },
  });
});

// ─── GET /api/v1/ai/conversations ────────────────────────────────────────────

router.get('/conversations', rbac('ai:chat'), async (req: Request, res: Response) => {
  const incidentId = req.query.incident_id as string | undefined;
  const limit = Math.min(Number(req.query.limit) || 20, 100);

  const filter: Record<string, unknown> = {
    tenant_id: req.tenantId,
    user_id: req.userId,
  };
  if (incidentId) {
    filter.incident_id = new Types.ObjectId(incidentId);
  }

  const conversations = await AIConversation.find(filter)
    .sort({ updated_at: -1 })
    .limit(limit)
    .select('title incident_id messages ai_model total_tokens created_at updated_at')
    .lean();

  const data = conversations.map((c: any) => ({
    id: c._id.toString(),
    title: c.title,
    incident_id: c.incident_id?.toString() || null,
    message_count: c.messages?.length || 0,
    model: c.ai_model,
    total_tokens: c.total_tokens,
    created_at: c.created_at,
    updated_at: c.updated_at,
  }));

  res.json({ data });
});

// ─── GET /api/v1/ai/conversations/:id ────────────────────────────────────────

router.get('/conversations/:id', rbac('ai:chat'), async (req: Request, res: Response) => {
  const conversation = await AIConversation.findOne({
    _id: req.params['id'],
    tenant_id: req.tenantId,
    user_id: req.userId,
  }).lean();

  if (!conversation) {
    throw AppError.notFound('Conversation');
  }

  res.json({
    id: (conversation as any)._id.toString(),
    title: conversation.title,
    incident_id: conversation.incident_id?.toString() || null,
    messages: conversation.messages.map((m) => ({
      role: m.role,
      content: m.content,
      timestamp: m.timestamp,
    })),
    model: conversation.ai_model,
    total_tokens: conversation.total_tokens,
    created_at: (conversation as any).created_at,
    updated_at: (conversation as any).updated_at,
  });
});

// ─── DELETE /api/v1/ai/conversations/:id ─────────────────────────────────────

router.delete('/conversations/:id', rbac('ai:chat'), async (req: Request, res: Response) => {
  const result = await AIConversation.deleteOne({
    _id: req.params['id'],
    tenant_id: req.tenantId,
    user_id: req.userId,
  });

  if (result.deletedCount === 0) {
    throw AppError.notFound('Conversation');
  }

  res.status(204).send();
});

export default router;
