import { AgentDefinition } from '../models/agent-definition.model';
import { logger } from '../utils/logger';

const AGENT_DEFINITIONS = [
  {
    slug: 'incident-triage',
    display_name: 'Incident Triage Agent',
    description: 'Auto-triage alerts, correlate related incidents, assign severity, and route to on-call responders.',
    long_description: 'Eliminates the alert-to-human-triage gap. Correlates incoming alerts with recent activity, deduplicates noise, auto-sets severity based on service tier and blast radius, assigns on-call responders from escalation policies, and generates triage summaries with investigation steps.',
    category: 'incident_response',
    icon: 'Zap',
    capabilities: ['incident.create', 'incident.update', 'incident.update_severity', 'incident.add_responder', 'incident.add_timeline_entry', 'notification.send'],
    triggers: ['alert.fired', 'incident.created'],
    required_scopes: ['incidents'],
    required_plan: 'business',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 29_900 },
    sort_order: 1,
  },
  {
    slug: 'incident-commander',
    display_name: 'Incident Commander Agent',
    description: 'AI incident commander for major incidents — monitors, coordinates, and ensures nothing falls through the cracks.',
    long_description: 'Acts as an AI incident commander for SEV-1/2 incidents. Monitors the timeline for staleness, suggests role assignments, detects stalled investigations, recommends escalation, suggests relevant runbooks, and drafts status updates.',
    category: 'incident_response',
    icon: 'Shield',
    capabilities: ['incident.add_timeline_entry', 'incident.add_responder', 'notification.send', 'escalation.trigger', 'runbook.suggest', 'status_page.draft_update'],
    triggers: ['incident.created', 'incident.severity_changed'],
    required_scopes: ['incidents', 'escalations'],
    required_plan: 'business',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 49_900 },
    is_beta: true,
    sort_order: 2,
  },
  {
    slug: 'rca-agent',
    display_name: 'Root Cause Analysis Agent',
    description: 'Auto-generate structured postmortems with root cause, contributing factors, and actionable follow-ups.',
    long_description: 'Analyzes the full incident timeline, metrics, changes, and past incidents to identify root cause with confidence scoring. Generates draft postmortems using the Swiss cheese model and creates follow-up tickets for each action item.',
    category: 'incident_response',
    icon: 'Search',
    capabilities: ['postmortem.create_draft', 'incident.add_timeline_entry', 'ticket.create'],
    triggers: ['incident.resolved'],
    required_scopes: ['incidents'],
    required_plan: 'starter',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 19_900 },
    sort_order: 3,
  },
  {
    slug: 'alert-intelligence',
    display_name: 'Alert Intelligence Agent',
    description: 'Reduce alert noise 5-10x with AI-powered correlation, deduplication, and flap detection.',
    long_description: 'Correlates related alerts by service affinity and time window, deduplicates identical alerts, detects flapping patterns, analyzes false-positive rates, and suggests threshold tuning. Turns a noisy alert stream into actionable signal.',
    category: 'observability',
    icon: 'BellRing',
    capabilities: ['alert.correlate', 'alert.suppress', 'alert_rule.suggest_update', 'incident.create', 'notification.send'],
    triggers: ['alert.fired'],
    required_scopes: [],
    required_plan: 'business',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 39_900 },
    sort_order: 4,
  },
  {
    slug: 'change-risk',
    display_name: 'Change Risk Agent',
    description: 'AI-powered change risk scoring, conflict detection, and auto-approval for low-risk standard changes.',
    long_description: 'Analyzes change descriptions, affected services, and historical outcomes to compute AI risk scores. Detects conflicts with overlapping changes, evaluates blast radius, suggests optimal implementation windows, and can auto-approve standard low-risk changes.',
    category: 'change_management',
    icon: 'GitPullRequest',
    capabilities: ['change.update_risk_score', 'change.add_conflict_warning', 'change.suggest_window', 'change.approve', 'notification.send'],
    triggers: ['change.submitted', 'change.scheduled'],
    required_scopes: [],
    required_plan: 'business',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 24_900 },
    sort_order: 5,
  },
  {
    slug: 'runbook-automation',
    display_name: 'Runbook Automation Agent',
    description: 'Match incidents to relevant runbooks and enable self-healing through automated execution.',
    long_description: 'Searches the runbook library for relevant matches based on incident symptoms, ranks by relevance, suggests execution, and oversees automated runbook execution. Enables self-healing for well-characterized issues.',
    category: 'automation',
    icon: 'BookOpen',
    capabilities: ['runbook.suggest', 'runbook.execute', 'incident.add_timeline_entry'],
    triggers: ['incident.created'],
    required_scopes: ['runbooks'],
    required_plan: 'business',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 34_900 },
    sort_order: 6,
  },
  {
    slug: 'comms-agent',
    display_name: 'Communication Agent',
    description: 'Auto-draft status page updates, stakeholder summaries, and consumer message replies.',
    long_description: 'Handles all incident communications — drafts customer-facing status page updates, generates executive summaries, drafts replies to consumer messages in the communication hub, and summarizes long threads.',
    category: 'communication',
    icon: 'MessageSquare',
    capabilities: ['status_page.draft_update', 'status_page.publish_update', 'thread.draft_reply', 'incident.add_timeline_entry', 'notification.send'],
    triggers: ['incident.created', 'incident.resolved', 'incident.status_changed', 'comms.inbound'],
    required_scopes: ['communications'],
    required_plan: 'starter',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 19_900 },
    sort_order: 7,
  },
  {
    slug: 'slo-guardian',
    display_name: 'SLO Guardian Agent',
    description: 'Proactive error budget monitoring, SLA breach prevention, and reliability recommendations.',
    long_description: 'Forecasts error budget exhaustion, alerts on fast burn rates, recommends protective actions (change freezes, capacity adds), tracks SLA compliance per consumer for providers, and generates weekly reliability reports.',
    category: 'reliability',
    icon: 'Gauge',
    capabilities: ['notification.send', 'ticket.create', 'incident.add_timeline_entry'],
    triggers: ['slo.budget_burned'],
    required_scopes: [],
    required_plan: 'business',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 24_900 },
    sort_order: 8,
  },
  {
    slug: 'oncall-wellness',
    display_name: 'On-Call Wellness Agent',
    description: 'Protect team health with workload monitoring, fatigue detection, and schedule optimization.',
    long_description: 'Tracks incident load per on-call person, detects uneven distribution and burnout risk, identifies coverage gaps, generates handoff summaries, and suggests schedule adjustments based on historical patterns.',
    category: 'people',
    icon: 'Heart',
    capabilities: ['notification.send', 'oncall_schedule.suggest_override', 'ticket.create'],
    triggers: ['oncall.rotation_changed', 'incident.resolved'],
    required_scopes: ['oncall'],
    required_plan: 'starter',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 14_900 },
    sort_order: 9,
  },
  {
    slug: 'knowledge-agent',
    display_name: 'Knowledge Agent',
    description: 'Organizational memory — answers questions, surfaces past incidents, and detects recurring patterns.',
    long_description: 'Indexes all platform data (incidents, postmortems, runbooks, changes) to answer questions, surface relevant context during incidents, detect recurring patterns, and help onboard new team members.',
    category: 'knowledge',
    icon: 'Brain',
    capabilities: ['incident.add_timeline_entry', 'notification.send', 'ticket.create'],
    triggers: ['incident.created'],
    required_scopes: [],
    required_plan: 'business',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 29_900 },
    sort_order: 10,
  },
  {
    slug: 'provider-intel',
    display_name: 'Provider Intelligence Agent',
    description: 'Cross-consumer intelligence for managed SRE — pattern detection, unified triage, SLA risk monitoring.',
    long_description: 'Detects cross-consumer patterns, prioritizes unified triage based on SLA commitments, generates consumer health scores, forecasts capacity needs, and suggests configurations for newly onboarded consumers.',
    category: 'managed_services',
    icon: 'Crown',
    capabilities: ['notification.send', 'ticket.create', 'slo.suggest'],
    triggers: ['incident.created', 'slo.budget_burned'],
    required_scopes: ['incidents'],
    required_plan: 'enterprise',
    tenant_type_restriction: 'provider',
    pricing: { monthly_cents: 59_900 },
    sort_order: 11,
  },
  {
    slug: 'security-compliance',
    display_name: 'Security & Compliance Agent',
    description: 'Automated security classification, compliance monitoring, audit reporting, and access anomaly detection.',
    long_description: 'Classifies security incidents, ensures process compliance (postmortems, approvals), detects access anomalies, verifies change policies, and generates SOC2/ISO27001 compliance reports from audit data.',
    category: 'governance',
    icon: 'ShieldCheck',
    capabilities: ['incident.update', 'notification.send', 'ticket.create'],
    triggers: ['incident.created'],
    required_scopes: [],
    required_plan: 'enterprise',
    tenant_type_restriction: 'any',
    pricing: { monthly_cents: 34_900 },
    sort_order: 12,
  },
];

export async function seedAgentDefinitions(): Promise<void> {
  try {
    const existingCount = await AgentDefinition.countDocuments();
    if (existingCount > 0) {
      logger.info(`Agent definitions already seeded (${existingCount} found), skipping`);
      return;
    }

    await AgentDefinition.insertMany(AGENT_DEFINITIONS);
    logger.info(`Seeded ${AGENT_DEFINITIONS.length} agent definitions`);
  } catch (err: any) {
    logger.error('Failed to seed agent definitions', { error: err.message });
  }
}
